[package]
name = "infrastructure"
version = "0.1.0"
authors = ["TRAN HUU DUC <duc.tran@doitsu.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
core = { path = "../core" }
